services:
  nginx:
    image: nginx:latest
    container_name: nginx-prueba
    ports:
      - "80:80"      
      - "443:443"            
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./web:/var/www/sitio1/html:ro
      - ./confidencial:/var/www/sitio2/html/confidencial:ro
      - ./certificados:/etc/nginx/ssl:ro
      - ./apache/web:/var/www/sitio_protegido:ro
    depends_on:
      - tomcat
      - apache
    networks:
      - red_docker


  apache:
    build:
      context: ./apache_correccion
      dockerfile: Dockerfile
    container_name: apache-ldap
    volumes:
      - ./apache/ldap.conf:/usr/local/apache2/conf.d/httpd-ldap.conf:ro
      - ./apache/web:/usr/local/apache2/htdocs_ldap:ro 
    networks:
      - red_docker

  tomcat:
    image: tomcat:9.0-jdk11-openjdk 
    container_name: tomcat-server
    volumes:
      - ./java/sample.war:/usr/local/tomcat/webapps/sample.war
    networks:
      - red_docker

networks:
  red_docker:
    driver: bridge