services:
  nginx:
    image: nginx:latest
    container_name: nginx-prueba
    ports:
      - "80:80"      
      - "443:443"            
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./web:/var/www/sitio1/html:ro
      - ./confidencial:/var/www/sitio2/html/confidencial:ro
      - ./certificados:/etc/nginx/ssl:ro
