services:
  web:
    build: .
    image: mi-app-django-compose 
    container_name: mi-django-app-compose 
    command: > 
      sh -c "python manage.py migrate &&
            gunicorn --bind 0.0.0.0:8000 --workers ${GUNICORN_WORKERS:-3} arbnb.wsgi:application"
    ports:
      - "8000:8000" 
    environment:
      SECRET_KEY: "pepe"
      DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      POSTGRES_DB: "base_datos_arbnb"
      POSTGRES_USER: "pepe"
      POSTGRES_PASSWORD: "pepe"
      POSTGRES_HOST: "bd" 
      POSTGRES_PORT: "5432"
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
    depends_on:
      - bd

  bd: 
    image: postgres:14-alpine 
    container_name: base_datos
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    environment:
      POSTGRES_DB: "base_datos_arbnb" 
      POSTGRES_USER: "pepe" 
      POSTGRES_PASSWORD: "pepe" 

volumes:
  postgres_data: