# Generated by Django 4.1.13 on 2025-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='comentario',
            field=models.CharField(default='comentario prueba', max_length=200),
            preserve_default=False,
        ),
    ]
