# Generated by Django 4.1.13 on 2025-05-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos_app', '0003_alquiler_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
